#!/bin/bash
sudo yum update
sudo yum install -y java-1.8.0-openjdk
sudo wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
sudo rpm --import http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
sudo yum install -y jenkins
sudo service jenkins start
sudo chkconfig --add jenkins



echo $PATH
/usr/local/bin/terraform -v
/usr/local/bin/terraform init
/usr/local/bin/terraform plan
/usr/local/bin/terraform apply -auto-approve
/usr/local/bin/terraform output instance_ip_addr
instance_ip_addr=$(/usr/local/bin/terraform output instance_ip_addr)
echo $instance_ip_addr
ssh ec2-user@$instance_ip_addr -o StrictHostKeyChecking=no
sudo yum update -y
sudo yum install -y java-1.8.0
sudo yum install -y git

